apiVersion: v1
kind: Service
metadata:
  labels:
    app: ql
  name: ql
spec:
  ports:
  - name: ql
    port: 8668
    protocol: TCP
    targetPort: 8668
  selector:
    app: ql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ql
  name: ql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ql
  template:
    metadata:
      labels:
        app: ql
    spec:
      containers:
        - env:
            - name: CACHE_QUERIES
              value: "False"
            - name: CRATE_HOST
              value: ql
            - name: LOGLEVEL
              value: DEBUG
            - name: QL_DEFAULT_DB
              value: ql
            - name: USE_GEOCODING
              value: "False"
          image: orchestracities/quantumleap:0.8.3
          name: quantumleap
          ports:
            - containerPort: 8668
              hostPort: 8668
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}