zookeeper:
  enabled: false
kraft:
  enabled: false
controller:
  replicaCount: 0
broker:
  replicaCount: 1
  extraConfig: "defaultReplicationFactor=1"
externalZookeeper:
  servers: zookeeper
tls:
  sslClientAuth: none
listeners:
  client:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT
extraEnvVars:
  - name: ALLOW_PLAINTEXT_LISTENER
    value: "yes"
  - name: KAFKA_CFG_BACKGROUND_THREADS
    value: "10"
  - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
    value: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CLIENT:PLAINTEXT"
  - name: KAFKA_CFG_ADVERTISED_LISTENERS
    value: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:9092,CLIENT://kafka-broker-headless:9092"