apiVersion: v1
kind: PersistentVolume
metadata:
  name: crate-db-pv-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/panagiotiskapsalis/PycharmProjects/MARTEL-PROJECTS/ACES.Perception/config/cratedb"