version: '3.3'

volumes:
  mongodb-data:
  cratedb-data:

networks:
  aces-perception:
    name: aces-perception

services:
  mongodb:
    image: mongo:4.4
    hostname: ${MONGO_HOSTNAME}
    container_name: ${MONGO_HOSTNAME}
    networks:
      - aces-perception
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=admin
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

  orion-cb:
    image: fiware/orion:3.10.1
    container_name: ${ORION_HOSTNAME}
    hostname: ${ORION_HOSTNAME}
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - aces-perception
    ports:
      - "1026:1026"
    command: -dbhost ${MONGO_HOSTNAME} -dbuser ${MONGO_INITDB_ROOT_USERNAME} -dbpwd ${MONGO_INITDB_ROOT_PASSWORD} -logLevel WARN

  crate-db:
    container_name: ${CRATE_HOSTNAME}
    hostname: ${CRATE_HOSTNAME}
    image: crate:4.5.1
    command: crate -Cauth.host_based.enabled=false -Ccluster.name=democluster -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"
    volumes:
      - cratedb-data:/data
    ports:
      - "4200:4200"
      - "4300:4300"
    networks:
      - aces-perception

  quantumleap:
    hostname: ${QLEAP_HOSTNAME}
    container_name: ${QLEAP_HOSTNAME}
    image: orchestracities/quantumleap:0.8.3
    depends_on:
      - crate-db
    networks:
      - aces-perception
    ports:
      - "8668:8668"
    environment:
      - QL_DEFAULT_DB=${CRATE_HOSTNAME}
      - CRATE_HOST=${CRATE_HOSTNAME}
      - USE_GEOCODING=False
      - CACHE_QUERIES=False
      - LOGLEVEL=DEBUG